### ISSUE TITLE
Incomplete Clone Doesn't Cleanup Dir

### ISSUE THREAD

**Issue by starcraftman** [starcraftman/vim-plug#17]
Move cleanup code from install() on Plugin, down into some rescue callable inside command.

**Comment by starcraftman** [comment]
Interesting, cleanup code seems to execute but sometimes the cmd fails saying path exists. Investigating further.

**Comment by junegunn** [comment]
Could it be because git and its child processes are still alive at the point you execute the cleanup code?
Ruby version explictly kills all the related processes on error
https://github.com/junegunn/vim-plug/blob/master/plug.vim#L1100-1104

**Comment by starcraftman** [comment]
@junegunn Plausible. I'm going to test this, also, should have had a pcmd.wait after the kill. Perhaps thats all that is needed. Sometimes the simple things slip by.

**Comment by starcraftman** [comment]
@junegunn I can confirm, the git processes aren't always terminated by time code comes around (it is failing on residual tmp_pack files). The root of the problem is the git processes aren't children of the python subprocess (or python would wait for them), so will have to either make them such or find another kill method. 

Have to love those threads & shell processes!

**Comment by junegunn** [comment]
@starcraftman It looks like you're stuck with the same issue I had when I had to painfully write this piece of code. https://github.com/junegunn/vim-plug/blob/4a96db89/plug.vim#L1006-1018

**Comment by starcraftman** [comment]
@junegunn Found an amazingly simple solution. I can execute the subprocess within a new process group, then send the signal to the entire group which includes all children. Seems to work always. Will push momentarily.

**Comment by starcraftman** [comment]
@junegunn Do you want to rerun your test with timeout = 1 now? I have run it several times and everything either completes or timesout for me. I believe this issue is resolved.

**Comment by junegunn** [comment]
@starcraftman Great! I think I should apply the same method to Ruby installer. I'll test it again today.

**Comment by starcraftman** [comment]
@junegunn Glad you like the idea. Hope this is fixed. If not, well I don't actually know why the process/children wouldn't die from sigterm across the group. That would be strange.

If it does unfortunately fail again, can you try adding time.sleep(1) or larger delays after the os.killpg. About only thing I think could be left is they don't die fast enough?
