### ISSUE TITLE
Need A Mac Tester

### ISSUE THREAD

**Issue by starcraftman** [starcraftman/vim-plug#2]
I can only test Linux + Windows.

**Comment by vheon** [comment]
here I am :), I'll start using from tomorrow morning and report any problem I will encounter :+1:

**Comment by starcraftman** [comment]
@vheon Thanks. I don't expect any huge problems, issues are enabled here if you run into any. 

Currently its a drop in replacement for main plug.vim. If your Vim is compiled with +python and +ruby my branch will invoke the python parallel installer over ruby. You can swap back by running PlugUpgrade.

**Comment by vheon** [comment]
I just read the code and a thing seems semantically different from the ruby version, but I'm not sure. I'll check tomorrow and report it here if it is confirmed.

**Comment by vheon** [comment]
@starcraftman I just downloaded your fork and try to `:PlugUpdate` and on my mac it doesn't work. I'll investigate further and open an issue.

**Comment by starcraftman** [comment]
@vheon thanks for trying. Also, when filling the issue can you be clear about if its the macgui version you used or just a normal terminal vim. I don't have experience with the mac version but its different than just doing a normal vim build on Mac right?

**Comment by starcraftman** [comment]
Closing this since @vheon is helping.
