### ISSUE TITLE
Study Changes Required for Python 2.6.x

### ISSUE THREAD

**Issue by starcraftman** [starcraftman/vim-plug#21]
Last stable production was 2.6.6, if supporting might be cutoff. Rest were security releases.

Known 2.7 issues:
'{}'.format() -> '{0}'
don't use sets at all?
with statement improved in 2.7

**Comment by starcraftman** [comment]
For now, I'm not planning to implement this. Instead I'll just make a wiki page on vim with python 2.7, with instructions for compiling.

**Comment by junegunn** [comment]
I'll leave the wiki of vim-plug open for unrestricted edit for a while. Feel free to add a page on python if you feel like it.

**Comment by starcraftman** [comment]
@junegunn Thanks, almost done my page. If you don't want to leave it open I can make a PR later. Working version > https://github.com/starcraftman/vim-plug/wiki/python

I don't have OSX, I assume default version of python/vim is 2.7/+python enabled?

**Comment by junegunn** [comment]
Does PR work with wiki pages as well? Anyway `/usr/bin/vim` has `+python`, `/usr/bin/python --version` gives 2.7.6.

**Comment by starcraftman** [comment]
@junegunn Not sure directly, but I could just use it to signal when my page was ready for copy over. Anyway, if your leaving it open, I'll edit it in by tomorrow. Late here.

**Comment by junegunn** [comment]
Sure, no hurries.

**Comment by starcraftman** [comment]
@junegunn Ok, I provided instructions for checking requirements on any platform. Script should work anywhere so long as they change the apt-get line. Should be enough for people with older pythons, they don't need to replace system one to take advantage. Tested and worked on lucid with 2.6.

**Comment by starcraftman** [comment]
Well i'm closing this. By the strict name, study is over. I don't really feel like doing the implementation changes and retesting everything. Also, don't think its in huge demand. Additionally, the wiki instructions should work for most people.

In hindsight, if I ever make another script probably going to test against 2.6 ish from the start, since it is easier to port forward.
