### ISSUE TITLE
Neovim Broken

### ISSUE THREAD

**Issue by starcraftman** [starcraftman/vim-plug#23]
On neovim:

```
Unhandled exception in thread started by <bound method PlugThread.__bootstrap of <PlugThread(PlugT-15, stopped 140 343022450432)>>
```

**Comment by vheon** [comment]
I get the same error on mac.

**Comment by starcraftman** [comment]
@vheon What I see is, it seems to fail in the trace whenever one of my threads requests vim.current.buffer, which happens when they use the callback. Seems to relate to how neovim implemented compatibility for if_pyth.

The line crashing the code: https://github.com/junegunn/vim-plug/blob/master/plug.vim#L1108

``` vim
[PlugT-15,19:44:54.963361] DeleteTrailingWhitespace: Dir /home/starcraftman/.nvim/bundle/DeleteTrailingWhitespace/
[PlugT-15,19:44:54.965270] + DeleteTrailingWhitespace: Installing ...
[PlugT-15,19:44:54.971276] x DeleteTrailingWhitespace: Trace:
Traceback (most recent call last):
  File "<string>", line 214, in manage
  File "<string>", line 239, in install
  File "<string>", line 282, in write
  File "<string>", line 90, in write
  File "<string>", line 105, in _write
  File "/usr/local/lib/python2.7/dist-packages/neovim/api/nvim.py", line 233, in buffer
    return self._session.request('vim_get_current_buffer')
  File "/usr/local/lib/python2.7/dist-packages/neovim/api/common.py", line 222, in request
    return walk(self._in, self._session.request(name, *args), self, name,
  File "/usr/local/lib/python2.7/dist-packages/neovim/msgpack_rpc/session.py", line 72, in request
    v = self._yielding_request(method, args)
  File "/usr/local/lib/python2.7/dist-packages/neovim/msgpack_rpc/session.py", line 137, in _yielding_request
    return parent.switch()
AttributeError: 'NoneType' object has no attribute 'switch'
```

This appears related to neovim/python-client#80 .

**Comment by starcraftman** [comment]
I've managed to get an almost fully working python installer on neovim on branch **nvim_py** . All buffer logic transfered to the main loop solves above isssue. 

Interrupt no longer works though (only on neovim). Otherwise, just a minor buffer glitch where order of plugins jumps around.

**Comment by starcraftman** [comment]
I think this branch has demonstrated a nice speed improvement over old version. Change comes from lock reduction. Only downside is CTRL + C seems to lag a bit. With about 50 plugins on my slow i3 notebook I see following times:

```vim
Vim + nvim_py
7.005593
6.959201
6.843147

Vim + master
7.487281
7.430914
7.631373
```

**Comment by starcraftman** [comment]
See latest PR on junegunn's. Closing.
